services:
  - type: web
    name: bliss-django
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bliss_website.wsgi:application --preload --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bliss_website.settings
      - key: PYTHON_VERSION
        value: 3.10.13
